### PR TITLE
Rewrite and improve the api wrapper

### PR DESCRIPTION
**Pull request by ghost**
first stable release 👀

### CODE REVIEW

**Review by io4 — APPROVED** [review]

**Comment by MicroDroid** [comment]
Thanks @io4 for the review!

I'll make a quick look at this within several hours and then I'll merge. Thanks, @devcat for your efforts.

**Comment by MicroDroid** [comment]
You can't really replace an entire repository with a pull request. Create a new library and maintain it, if it goes well we could move it to the org and deprecate this.

**Comment by ghost** [comment]
What is the point of versions then

**Comment by MicroDroid** [comment]
@devcat Versions are for changes, not complete rewrites

**Comment by MicroDroid** [comment]
<@440580043203280906>

**Comment by ghost** [comment]
Major versions are for big changes even full rewrites

**Pull request closed without merging**
